services:

  frontend:
    build: ./to-do-list-app
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./to-do-list-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: temp_pwd_1
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: temp_pwd_1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: